/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: c50764b9a90a921755b4bd87a9f0bc23)
interface __BaseEnv_Env {
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index-v10");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
