import type { Problem } from "./data";

const styles = `
:root{--bg:#f6f8fb;--card:#fff;--text:#162033;--muted:#667085;--line:#e6eaf0;--accent:#1f6feb;--accent2:#1557b0;--ok:#137333;--warn:#9a6700;--shadow:0 12px 32px rgba(15,23,42,.08)}
*{box-sizing:border-box}body{margin:0;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;background:var(--bg);color:var(--text)}a{color:inherit;text-decoration:none}.wrap{width:min(1120px,calc(100% - 32px));margin:auto}.topbar{padding:20px 0}.brand{font-weight:800;letter-spacing:-.03em;font-size:1.2rem}.brand span{color:var(--accent)}.hero{padding:66px 0 38px}.hero h1{font-size:clamp(2.3rem,6vw,4.7rem);line-height:.98;letter-spacing:-.055em;margin:0 0 18px;max-width:880px}.hero p{font-size:1.08rem;color:var(--muted);max-width:720px;line-height:1.65}.search{display:grid;grid-template-columns:1fr auto;gap:10px;background:var(--card);padding:10px;border:1px solid var(--line);border-radius:18px;box-shadow:var(--shadow);margin-top:28px}.search input{border:0;outline:0;padding:16px;font-size:1.03rem;background:transparent;min-width:0}.search button{border:0;border-radius:12px;background:var(--accent);color:white;padding:0 22px;font-weight:700;cursor:pointer}.search button:hover{background:var(--accent2)}.chips{display:flex;flex-wrap:wrap;gap:8px;margin:16px 0 0}.chip{font-size:.9rem;background:white;border:1px solid var(--line);padding:8px 11px;border-radius:999px;color:#475467}.section{padding:34px 0}.section h2{font-size:1.55rem;letter-spacing:-.03em;margin:0 0 18px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.card{background:var(--card);border:1px solid var(--line);border-radius:16px;padding:18px;box-shadow:0 3px 14px rgba(15,23,42,.035)}.card h3{margin:0 0 8px;font-size:1.03rem}.card p{margin:0;color:var(--muted);line-height:1.5;font-size:.94rem}.result-list{display:grid;gap:12px}.result{display:block;background:#fff;border:1px solid var(--line);padding:18px;border-radius:15px}.result strong{display:block;margin-bottom:5px}.result small{color:var(--muted)}.breadcrumb{font-size:.9rem;color:var(--muted);margin-bottom:18px}.problem{max-width:820px}.problem h1{font-size:clamp(2rem,4vw,3.25rem);letter-spacing:-.045em;line-height:1.04}.lead{font-size:1.08rem;color:var(--muted);line-height:1.65}.route{margin:26px 0;display:grid;gap:10px}.step{background:white;border:1px solid var(--line);padding:18px;border-radius:14px}.step b{display:block;color:var(--accent);font-size:.78rem;text-transform:uppercase;letter-spacing:.08em;margin-bottom:6px}.notice{background:#fff8e7;border:1px solid #f2d38c;color:#6b4d00;padding:16px;border-radius:14px}.status{display:inline-flex;align-items:center;gap:7px;font-size:.86rem;padding:7px 10px;border-radius:999px;background:#f2f4f7;color:#475467}.footer{border-top:1px solid var(--line);margin-top:48px;padding:26px 0 44px;color:var(--muted);font-size:.9rem}.empty{padding:28px;background:#fff;border:1px dashed #cfd6df;border-radius:16px}.kicker{font-weight:700;color:var(--accent);font-size:.82rem;text-transform:uppercase;letter-spacing:.1em}.safe{background:#edf7ef;color:var(--ok)}
@media(max-width:760px){.grid{grid-template-columns:1fr}.hero{padding-top:34px}.search{grid-template-columns:1fr}.search button{padding:14px 18px}.wrap{width:min(100% - 22px,1120px)}}
`;

function esc(value: string): string {
  return value.replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c] || c));
}

function shell(title: string, description: string, body: string): string {
  const canonical = "https://nereyebasvurulur.com";
  return `<!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><meta name="robots" content="noindex,nofollow"><link rel="canonical" href="${canonical}"><style>${styles}</style></head><body><header class="topbar"><div class="wrap"><a class="brand" href="/">Nereye <span>Başvurulur?</span></a></div></header>${body}<footer class="footer"><div class="wrap">Geliştirme sürümü. Bu içerikler resmî kaynak doğrulaması tamamlanmadan yayımlanmayacaktır.</div></footer></body></html>`;
}

export function renderHome(categories: string[], problems: Problem[]): string {
  const catCards = categories.slice(0, 12).map(c => `<div class="card"><h3>${esc(c)}</h3><p>Bu alandaki sorunlar için doğru kurum ve başvuru rotaları.</p></div>`).join("");
  const examples = problems.slice(0, 5).map(p => `<a class="result" href="/konu/${p.slug}"><strong>${esc(p.title)}</strong><small>${esc(p.category)}</small></a>`).join("");
  return shell("Nereye Başvurulur? | Doğru kurumu bulun", "Sorununuzu yazın; doğru kurum, başvuru kanalı ve sonraki adımları bulun.", `<main><section class="hero"><div class="wrap"><div class="kicker">Başvuru yönlendirme motoru</div><h1>Sorununuzu yazın. Doğru kapıyı birlikte bulalım.</h1><p>Şikâyet, bildirim, itiraz veya başvuru için hangi kurumun yetkili olduğunu, hangi kanaldan başvurabileceğinizi ve sonuç alamazsanız sonraki adımı gösterir.</p><form class="search" action="/ara" method="get"><input name="q" autocomplete="off" placeholder="Örn. Sokak lambası yanmıyor" aria-label="Sorununuzu yazın"><button type="submit">Nereye başvurmalıyım?</button></form><div class="chips"><span class="chip">Komşu gürültüsü</span><span class="chip">Bozuk yol</span><span class="chip">Kayıp kargo</span><span class="chip">Kaçak yapı</span></div></div></section><section class="section"><div class="wrap"><h2>Başvuru alanları</h2><div class="grid">${catCards}</div></div></section><section class="section"><div class="wrap"><h2>Örnek sorunlar</h2><div class="result-list">${examples}</div></div></section></main>`);
}

export function renderSearch(query: string, results: Problem[]): string {
  const list = results.length ? results.map(p => `<a class="result" href="/konu/${p.slug}"><strong>${esc(p.title)}</strong><small>${esc(p.summary)}</small></a>`).join("") : `<div class="empty"><strong>Henüz eşleşen bir başvuru rotası yok.</strong><p>Bu sorgu ileride sorun veri tabanına eklenmek üzere kaydedilebilir.</p></div>`;
  return shell(`${query || "Arama"} | Nereye Başvurulur?`, "Başvuru rotası arama sonuçları.", `<main class="section"><div class="wrap"><div class="breadcrumb"><a href="/">Ana sayfa</a> / Arama</div><h1>“${esc(query)}” için sonuçlar</h1><form class="search" action="/ara" method="get"><input name="q" value="${esc(query)}" aria-label="Arama"><button type="submit">Ara</button></form><div class="section result-list">${list}</div></div></main>`);
}

export function renderProblem(problem: Problem): string {
  return shell(`${problem.title} | Nereye Başvurulur?`, problem.summary, `<main class="section"><div class="wrap problem"><div class="breadcrumb"><a href="/">Ana sayfa</a> / ${esc(problem.category)}</div><span class="status">${problem.verified ? "✓ Resmî kaynaklarla doğrulandı" : "Taslak · doğrulama bekliyor"}</span><h1>${esc(problem.title)}</h1><p class="lead">${esc(problem.summary)}</p><div class="route"><div class="step"><b>1. Adım</b>${esc(problem.firstStep)}</div><div class="step"><b>Sonraki adım</b>${esc(problem.nextStep)}</div></div>${problem.caution ? `<div class="notice"><strong>Önemli:</strong> ${esc(problem.caution)}</div>` : ""}<section class="section"><h2>Yayın standardı</h2><p class="lead">Bu rota, ilgili resmî kurum ve mevzuat kaynakları doğrulandıktan sonra canlı sitede yayımlanacaktır. Taslak kayıtlar arama motorlarına açılmaz.</p></section></div></main>`);
}

export function renderNotFound(): string {
  return shell("Sayfa bulunamadı | Nereye Başvurulur?", "Aradığınız sayfa bulunamadı.", `<main class="section"><div class="wrap"><div class="empty"><h1>Bu rota henüz yok.</h1><p>Ana sayfadan sorununuzu arayabilirsiniz.</p><p><a href="/"><strong>← Ana sayfaya dön</strong></a></p></div></div></main>`);
}
